apiVersion: v1
kind: Service
metadata:
  name:  graphql
  labels:
    app: graphql
spec:
  selector:
    app:  graphql
  type:  NodePort
  ports:
  - port: 4000
    targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graphql
  labels:
    app: graphql
spec:
  selector:
    matchLabels:
      app: graphql
  template:
    metadata:
      labels:
        app: graphql
    spec:
      containers:
      - name: graphql
        image: alecwest/toy-book-app-graphql:1.0.0
        imagePullPolicy: "Always"
        ports:
        - containerPort: 4000
          name: graphql
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
---
