apiVersion: v1
kind: Service
metadata:
  name:  reviews
  labels:
    app: reviews
spec:
  selector:
    app:  reviews
  type:  ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  labels:
    app: reviews
spec:
  selector:
    matchLabels:
      app: reviews
  template:
    metadata:
      labels:
        app: reviews
    spec:
      containers:
      - name: reviews
        image: alecwest/toy-book-app-reviews:0.0.1-SNAPSHOT
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
          name: reviews
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
---
