apiVersion: v1
kind: Service
metadata:
  name:  catalog
  labels:
    app: catalog
spec:
  selector:
    app:  catalog
  type:  ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalog
  labels:
    app: catalog
spec:
  selector:
    matchLabels:
      app: catalog
  template:
    metadata:
      labels:
        app: catalog
    spec:
      containers:
      - name: catalog
        image: alecwest/toy-book-app-catalog:0.0.1-SNAPSHOT
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
          name: catalog
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
---
