apiVersion: v1
kind: Service
metadata:
  name:  users
  labels:
    app: users
spec:
  selector:
    app:  users
  type:  ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
spec:
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
      - name: users
        image: alecwest/toy-book-app-users:0.0.1-SNAPSHOT
        imagePullPolicy: "Always"
        ports:
        - containerPort: 8080
          name: users
        resources:
          limits:
            memory: "768Mi"
            cpu: "500m"
---
