apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-claim0
  labels:
    app: postgres
    tier: database
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 8Gi
  accessModes:
    - ReadWriteOnce
